#!/usr/bin/env python
"""
motocommand: Connect to a YASNAC ERC and send system control command(s)
"""
import argparse
import sys

import erc


def main():
    """
    primary function for command-line execution. return an exit status integer
    or a bool type (where True indicates successful exection)
    """
    argp = argparse.ArgumentParser(description=(
        "Connect to a YASNAC ERC and send system control command(s)"))
    argp.add_argument('command', nargs="+", help=(
        "A command to send to the ERC controller"))
    argp.add_argument('-d', '--debug', action="store_true", help=(
        "Enable transaction debugging output"))
    args = argp.parse_args()

    # now actually do stuff
    robot = erc.ERC()
    erc.DEBUG = args.debug
    for command in args.command:
        result = robot.system_control_command(command)
        if result:
            print ",".join(result)

    return True


if __name__ == '__main__':
    RESULT = main()
    sys.exit(int(not RESULT if isinstance(RESULT, bool) else RESULT))
